apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-app-controller
rules:
  - apiGroups: ["", "apps", "extensions", "argoproj.io"]
    resources: ["pods", "services", "deployments", "replicasets", "statefulsets", "applications", "configmaps", "secrets", "ingresses"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
